# Generated by Django 2.2.7 on 2019-12-01 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
    ]
