# Generated by Django 2.2.7 on 2019-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.FileField(default='book-cover-placeholder.png', upload_to=''),
        ),
    ]
